[admiral]
items = ["over", "left", "workspaces", "pad", "right", "music", "coover"]

[workspaces]
path = "./i3_workspaces.py default"

[music]
path = "./music.sh"
reload = 1

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[over]
path = "echo '%{+u}'"
static = true

[coover]
path = "echo '%{-u}'"
static = true

[pad]
path = "echo '                                                                                                                                                                                                                                                                      '"
static = true
