[admiral]
items = ["left", "workspaces"]

[workspaces]
path = "./i3_workspaces.py HDMI2,DP1"

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true
