variables:
  primary: magenta
  secondary: green
  tertiary: red
  special: yellow
  transparency: 80
  fontName: PragmataPro Mono
  fontSize: 14
plugins:
  parsers:
    - themer.parsers.SweylaColorParser
    - themer.parsers.WallhavenColorParser
    - themer.parsers.KmeansColorParser
    - themer.parsers.CachedColorParser
  # - themer.parsers.vim.VimColorParser
    - themer.ColorParser
  activators:
    - themer.activators.wallfix.WallfixActivator
    - themer.activators.i3.I3Activator
  # - themer.activators.acyl.ACYLActivator
files:
  Xdefaults.tpl: Xdefaults
  index.tpl: index.html
  i3.tpl: i3.conf
  rofi.tpl: rofi
  dunst.tpl: dunstrc
